"""Compiling a configured Tampermonkey bridge (proxy/userscripts.py + its route).

What matters here is that the substitution is *load-bearing*: the generated
script is pasted straight into Tampermonkey, so a silently-unsubstituted
constant would point every request at 127.0.0.1 on a machine that is not the
server, and look exactly like "the server is down". Hence the anchor checks --
rename a constant in config.js and these fail rather than the install.
"""

from __future__ import annotations

import pytest

from proxy import userscripts


def compiled(**kwargs) -> str:
    return userscripts.compile_userscript("jai", **kwargs)


def test_unconfigured_output_matches_the_checked_in_bundle():
    """`make compile` and the generator are the same code path -- if they drift,
    the repo's .user.js stops matching its sources."""
    for spec in userscripts.SPECS.values():
        on_disk = (userscripts.USERSCRIPT_DIR / spec.filename).read_text(encoding="utf-8")
        assert userscripts.compile_userscript(spec) == on_disk


def test_server_url_is_substituted_and_normalized():
    source = compiled(server_url="http://192.168.1.50:8000/")
    # Trailing slash stripped -- every call is SERVER + "/some/path".
    assert 'const DEFAULT_SERVER = "http://192.168.1.50:8000";' in source
    assert 'const DEFAULT_SERVER = "http://127.0.0.1:8000";' not in source


def test_tag_filter_is_substituted():
    source = compiled(include_tags=["female", "  "], exclude_tags=["futa", "futa"])
    assert 'include: ["female"],' in source
    assert 'exclude: ["futa"],' in source
    # The source defaults must be gone, not merely joined by new ones.
    assert "demihumanuser" not in source


def test_empty_include_list_means_export_everything():
    """An empty list is a real setting, not "unset" -- it must survive rather
    than falling back to the source's `["female"]`."""
    source = compiled(include_tags=[], exclude_tags=[])
    assert "include: [],\n    exclude: [],\n" in source


def test_a_generated_script_records_what_was_baked_in():
    source = compiled(server_url="http://nas:8000", include_tags=["female"], exclude_tags=[])
    assert "GENERATED by the archive server" in source
    assert "//   server:  http://nas:8000" in source
    assert "//   exclude: (nothing)" in source
    # Still a valid Tampermonkey script: the note sits *below* the banner block.
    assert source.index("// ==/UserScript==") < source.index("GENERATED")


def test_the_banner_and_iife_wrapper_survive():
    source = compiled(server_url="http://nas:8000")
    assert source.startswith("// ==UserScript==")
    assert '(function () {\n  "use strict";' in source
    assert source.endswith("})();\n")


@pytest.mark.parametrize(
    "bad",
    [
        "",
        "   ",
        "nas:8000",  # no scheme -- the most likely typo, and it would compile fine
        'http://nas:8000"; alert(1); //',  # would close the string literal
        "http://nas:8000\nfoo",
    ],
)
def test_a_server_url_that_is_not_a_url_is_refused(bad):
    with pytest.raises(userscripts.UserscriptError):
        compiled(server_url=bad)


def test_saucepan_has_no_tag_filter_and_passing_one_is_harmless():
    """The UI keeps one saved filter for both bridges, so it sends the tags
    either way; the bridge without a bulk sweep just ignores them."""
    source = userscripts.compile_userscript("saucepan", include_tags=["female"])
    assert "BULK_TAG_FILTER" not in source
    # No overrides that apply -> no GENERATED note either.
    assert "GENERATED" not in source


def test_a_renamed_constant_fails_loudly(monkeypatch):
    monkeypatch.setattr(userscripts, "_SERVER_RE", userscripts.re.compile(r"(?P<head>nothing matches)"))
    with pytest.raises(userscripts.UserscriptError, match="DEFAULT_SERVER"):
        compiled(server_url="http://nas:8000")


def test_unknown_script_key():
    with pytest.raises(userscripts.UserscriptError, match="unknown userscript"):
        userscripts.compile_userscript("nope")


# --- the route -------------------------------------------------------------


def test_listing_advertises_both_bridges(client):
    body = client.get("/api/v1/userscripts").json()
    by_key = {row["key"]: row for row in body}
    assert set(by_key) == {"jai", "saucepan"}
    assert by_key["jai"]["supports_tag_filter"] is True
    assert by_key["saucepan"]["supports_tag_filter"] is False
    assert by_key["jai"]["filename"] == "jai-proxy-bridge.user.js"


def test_generate_returns_the_configured_source(client):
    response = client.post(
        "/api/v1/userscripts/jai",
        json={"server_url": "http://192.168.1.50:8000", "include_tags": [], "exclude_tags": ["futa"]},
    )
    assert response.status_code == 200
    body = response.json()
    assert body["filename"] == "jai-proxy-bridge.user.js"
    assert 'const DEFAULT_SERVER = "http://192.168.1.50:8000";' in body["source"]
    assert 'exclude: ["futa"],' in body["source"]
    assert body["bytes"] == len(body["source"].encode("utf-8"))


def test_generate_with_no_overrides_is_the_plain_bundle(client):
    body = client.post("/api/v1/userscripts/saucepan", json={}).json()
    assert body["source"] == userscripts.compile_userscript("saucepan")


def test_a_bad_url_is_the_users_mistake_not_a_server_error(client):
    response = client.post("/api/v1/userscripts/jai", json={"server_url": "nas:8000"})
    assert response.status_code == 400
    assert "server URL" in response.json()["detail"]


def test_unknown_key_404s(client):
    assert client.post("/api/v1/userscripts/nope", json={}).status_code == 404
